---
network_ports:
  - switches:
      - s1-leaf1
    switch_ports:
      - Ethernet4
    enabled: true
    description: test eth4 trunk port
    mtu:
    vlans: "20,2300,2301,2302"
    profile: int_trunk_host
  - switches:
      - s1-leaf1
    switch_ports:
      - Ethernet6
    enabled: true
    mtu: 9000
    profile: int_routed_host
    structured_config:
      ip_address: 10.192.16.254/24
      vrf: bluevrf
      description: test eth6 routed port
      mtu:
